#!/bin/bash -e

case "$1" in
  configure)

  # conffiles
  . /usr/share/yavdr/helpers/conffiles
  install_conffile yavdr-backend-base /etc/default/backend
  install_conffile yavdr-backend-base /etc/init/backend.conf
  install_conffile yavdr-backend-base /etc/init/backend-dummy.conf

  # prefill hdf
  . /usr/share/yavdr/helpers/hdf_prefill
  hdf_prefill "backend.default" "dummy"

  # temlate files
  yavdr-template-backend

  ;;

esac

exit 0

