#!/bin/bash -e

/usr/bin/process-template --owner root --group root --mode 0644 /etc/default/backend
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/backend.conf

cd /usr/share/yavdr/backends/
for FRONTEND in *; do
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/init/backend-$FRONTEND.conf
done
