#!/bin/bash -e

/usr/bin/process-template --owner root --group root --mode 0644 /etc/default/backend
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/backend.conf

for BACKEND in `yavdr-list-backend-modules`; do
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/init/backend-$BACKEND.conf
done
